/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Classes.Block;
import java.awt.Dimension;
import java.awt.GridBagConstraints;

/**
 *
 * @author Juan
 */
public class BlockComponent extends javax.swing.JPanel {

    
    public BlockComponent(int id, Block block) {
        initComponents();
        blockID.setText(Integer.toString(id));
        if(block.getNext() == null){
            next.setText("");
        }
        else{
            next.setText(Integer.toString(block.getNext()));            
        }                
    }
    
    @Override
    public Dimension getPreferredSize() {
        return new Dimension(100, 50); // Ajusta el tamaño según tus necesidades
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        blockID = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        next = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        blockID.setText("num");
        jPanel1.add(blockID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 50));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        next.setText("Next");
        jPanel2.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 50, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blockID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel next;
    // End of variables declaration//GEN-END:variables
}
