/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Classes.Block;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import javax.swing.JPanel;

/**
 *
 * @author Juan
 */
public class BlockComponent extends javax.swing.JPanel {

    
    public BlockComponent(int id, Block block) {
        initComponents();
        blockID.setText(Integer.toString(id));
        if(block.getNext() == null){
            next.setText("");
        }
        else{
            next.setText(Integer.toString(block.getNext()));            
        }                
    }
    
    @Override
    public Dimension getPreferredSize() {
        return new Dimension(100, 50); // Ajusta el tamaño según tus necesidades
    }
    
     public static Color calculateLabelColor(Color color) {
        int red = color.getRed();
        int green = color.getGreen();
        int blue = color.getBlue();

        // Calcular la luminosidad
        double brightness = 0.2126 * red + 0.7152 * green + 0.0722 * blue;

        // Definir el umbral
        int threshold = 128;

        // Determinar el color del texto
        if (brightness < threshold) {
            return Color.WHITE; // Color de texto blanco para fondos oscuros
        } else {
            return Color.BLACK; // Color de texto negro para fondos claros
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        blockID = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        next = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        blockID.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        blockID.setText("num");
        background.add(blockID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 50));

        jPanel2.setBackground(new java.awt.Color(239, 239, 239));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        next.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        next.setText("Next");
        jPanel2.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 50, 50));
    }// </editor-fold>//GEN-END:initComponents
    

    public void setBackgroundColor(Integer[] color) {
        if(color != null){
            this.background.setBackground(new Color(color[0], color[1], color[2]));   
            Color labelColor = calculateLabelColor(new Color(color[0], color[1], color[2]));
            blockID.setForeground(labelColor);
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel blockID;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel next;
    // End of variables declaration//GEN-END:variables
}
