/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Util;
import DataStructures.List;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.concurrent.Semaphore;
import javax.swing.SwingUtilities;

/**
 *
 * @author Juan
 */
public class LoginView extends javax.swing.JFrame {

    //Para la terminal
    private int inputLength;
    private String currentInput;
    private List<String> inputs = new List();
    private List<String> outputs = new List();
    private Semaphore sem = new Semaphore(1);
    
    public LoginView() {
        initComponents();        
        init();
        this.setLocationRelativeTo(null);
    }
    
    public void init(){
        
        terminal.setCaretPosition(terminal.getText().length());
        currentInput = "Tipos de usuario\n1. Administrador\n2. Usuario\n\nIngrese el numero de la opcion deseada: ";
        inputLength = currentInput.length();
        
        // Iniciar un hilo de trabajo para manejar la entrada de la terminal
//        new Thread(() -> {
//            try {
//                while (true) {
//                    sem.acquire();
//                    SwingUtilities.invokeLater(() -> handleInput());
//                }
//            } catch (InterruptedException e) {
//                e.printStackTrace();
//            }
//        }).start();
    }
    
    public void handleInput(){
        String inputStr = inputs.pop(0);
        SwingUtilities.invokeLater(() -> {
            terminal.setText(inputStr);
            terminal.setEditable(true);
            terminal.setCaretColor(Color.WHITE);
            terminal.requestFocusInWindow();
            inputLength = inputStr.length();
            currentInput = inputStr;
        });        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttom = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        terminal = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        top.setBackground(new java.awt.Color(0, 19, 66));
        top.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido al Sistema de Archivos");
        top.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        background.add(top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 60));

        buttom.setBackground(new java.awt.Color(0, 15, 36));
        buttom.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        buttom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        terminal.setBackground(new java.awt.Color(0, 15, 36));
        terminal.setColumns(20);
        terminal.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        terminal.setForeground(new java.awt.Color(255, 255, 255));
        terminal.setRows(5);
        terminal.setText("Tipos de usuario\n1. Administrador\n2. Usuario\n\nIngrese el numero de la opcion deseada: ");
        terminal.setBorder(null);
        terminal.setCaretColor(new java.awt.Color(255, 255, 255));
        terminal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                terminalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                terminalKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(terminal);

        buttom.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 480, 260));

        background.add(buttom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 520, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void terminalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_terminalKeyPressed
        //Si se presiona enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            evt.consume();
            
            String output = terminal.getText().split(":")[1].trim();
                        
            if(!Util.isNumeric(output) || (Integer.parseInt(output) != 1 && Integer.parseInt(output) != 2)){
                String str = "Tipos de usuario\n1. Administrador\n2. Usuario\n\n";
                str += "Error: Valor ingresado no valido\nIngrese el numero de la opcion deseada: ";
                terminal.setText(str);
                return;
            }                        
            
            if(Integer.parseInt(output) == 1){
                MainView mv = new MainView(true);
                mv.setVisible(true);
            }
            else if(Integer.parseInt(output) == 2){
                MainView mv = new MainView(false);
                mv.setVisible(true);
            }
            this.dispose();
            
        }
    }//GEN-LAST:event_terminalKeyPressed

    private void terminalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_terminalKeyTyped
        //Si se presiona backspace
        if (evt.getKeyChar() == '\b') {             
            if ((terminal.getCaret().getDot() <= inputLength) && (terminal.isEditable())) {
                terminal.setText(currentInput);
            }
        }
    }//GEN-LAST:event_terminalKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel buttom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea terminal;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
